import { FunctionComponent, useEffect } from "react";
import styles from "../../modal/dropdownModal.module.scss";

interface SendToVendorModalProps {
  isVisible: boolean;
  onClose: () => void;
  onApply?: () => void;
}

const SendToVendorModal: FunctionComponent<SendToVendorModalProps> = ({
  isVisible,
  onClose,
  // onApply
}) => {
  useEffect(() => {
    if (isVisible) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "auto";
    }

    return () => {
      document.body.style.overflow = "auto";
    };
  }, [isVisible]);

  if (!isVisible) return null;
  return (
    <div className={styles.modalBackdrop} onClick={onClose}>
      <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
        <div>
          <div className="relative flex items-center justify-between mb-4 border-b border-gray-300 pb-4">
            <div className="text-center flex-1">
              <p className="text-xl font-semibold">Send PO to Vendor</p>
              <p>Send PO Letter by email to vendor</p>
            </div>

            <button
              onClick={onClose}
              className="ml-auto text-gray-600 bg-white"
            >
              X
            </button>
          </div>
          <div
            className="text-left  mt-4 cursor-pointer overflow-y-scroll mb-4 border-b border-gray-300 pb-4"
            style={{ height: "12rem" }}
          >
            {/* content  */}
            <div className="text-left">
              <p>Dear,</p>
              <p>Vendor name</p>
              <p className="my-4">
                Below is our PO Letter for ordering (xxxx).
              </p>
              <p className="mb-4">Thank you.</p>
              <p>
                <i>
                  {" "}
                  This email was generated by the system. Please do not reply.
                </i>
              </p>
            </div>
          </div>
          {/* button  */}
          <a href="mailto:emailvendor@gmail.com">
            <button className={`${styles.applyButton} w-full`}>
              Send Email (emailvendor@gmail.com)
            </button>
          </a>
        </div>
      </div>
    </div>
  );
};

export default SendToVendorModal;
